#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { listSlugs, projectRoot } from "./lib-slugs.mjs";

const root = projectRoot();
const slugs = listSlugs();
const out = path.join(root, "dist/track.py");

function read(p) {
  return fs.readFileSync(p, "utf8");
}

const banner = `#!/usr/bin/env python3
# AUTO-GENERATED by scripts/build-python.mjs — edit scrapers/ and runtime/python/, then npm run build
# Make executable: chmod +x track.py
"""IranCrypto Tracker — single-file API-only collector (Python).

Deploy: copy this file + logs/. No Mongo, no pip deps.
"""
from __future__ import annotations
`;

let helpers = read(path.join(root, "runtime/python/helpers.py"));
helpers = helpers.replace(/^#!\/usr\/bin\/env python3\n/, "");
helpers = helpers.replace(/^# Make executable:.*\n/, "");
if (helpers.trimStart().startsWith('"""')) {
  const end = helpers.indexOf('"""', 3);
  if (end !== -1) {
    helpers = helpers.slice(end + 3).replace(/^\n+/, "");
  }
}
helpers = helpers.replace(/^from __future__ import annotations\n/, "");

const parts = [banner, helpers.trimEnd(), "\n\n# ===== scrapers =====\n"];
for (const slug of slugs) {
  let scrape = read(path.join(root, "scrapers", slug, "scrape.py"));
  scrape = scrape.replace(/^from __future__ import annotations\n/, "");
  scrape = scrape.replace(/^from typing import .*\n/gm, "");
  parts.push(`\n# --- ${slug} ---\n`, scrape.trimEnd());
}
parts.push(
  "\n\n# ===== registry =====\n",
  read(path.join(root, "generated/python-scraper-registry.py")).trimEnd(),
  "\n\n# ===== orchestrator + main =====\n",
  read(path.join(root, "runtime/python/orchestrator.py")).trimEnd(),
  "\n"
);

fs.writeFileSync(out, parts.join("\n"));
fs.chmodSync(out, 0o755);
console.log(`Wrote dist/track.py (${slugs.length} scrapers)`);
